### ISSUE TITLE
deploy instructions

### ISSUE THREAD

**Issue by benjyz** [nos/create-nos-dapp#32]
yarn build generates index.html but it does not find the javascript? index.html in console shows 
`Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by DalderupMaurice** [comment]
Please fill in the issue template and/or provide some more info. We can not help with the limited amount of info. 
Feel free to reopen

**Comment by jeroenptrs** [comment]
@benjyz please refrain from deleting the issue template. Issues/PR's will be autoclosed.

To provide further insight to your question, you probably moved/renamed index.jsx in your index.html, which is why you get the file not found error
