### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ianaz** [nos/create-nos-dapp#9]
## Expected Behavior
I should be able to create a Reactapp under Linux

## Current Behavior
When I run `npm run start` I get 

```
Success: Created new project folder My-nOS-dApp
{ Error: ENOENT: no such file or directory, lstat '/home/ianaz/workspace/my-dapp/lib/..\packages\reactjs'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ianaz/workspace/my-dapp/lib/..\\packages\\reactjs' }
Done in 5.07s.
```

## Possible Solution
I think that's because of the backslashes. Using normal slashes could fix. 

## Your Environment
Linux 4.13.0-38-generic 43~16.04.1-Ubuntu 64bit GNU/Linux
* NodeJS 8.10

I'll try the possible solution right now and create a PR

**Comment by ianaz** [comment]
Created #10

**Comment by DalderupMaurice** [comment]
Good catch! 
It was previously only tested on windows - but the CLI tool needs some more refactoring before we publish it 😄
